### ISSUE TITLE
LostCore - Database GeoIP2

### ISSUE THREAD

**Issue by lolmanz0** [LostTeam/LostVIP#2]
Sorry that I am writing there but there is not Issues section on LostCore. I have this error.

"The file "GeoIP2-Country.mmdb" does not exist or is not readable." (EXCEPTION) in "/67-LostCore_v0-346e5/src/MaxMind/Db/Reader" at line 45

I know it is because there is not database. But I do not know how to create this database. Please, can you help me? This is not like MySQL.

**Comment by jasonwynn10** [comment]
Please leave an issue in the appropriate repository
